baseURL = 'https://example.org/'
languageCode = 'ru-ru'
title = 'selfdoor blog'

theme = "hugo-theme-yuminos"

[params]
    relatedMax = 5
    [params.comments]
        enabled = true
    [params.comments.giscus]
        repo = "shlyapp/my-hugo-blog"
        repoID = "R_kgDOPDscKQ"
        category = "Announcements"
        categoryID = "DIC_kwDOPDscKc4CsMQv"
        mapping = "title"
        reactionsEnabled = 1
        emitMetadata = 0
        lazy = false
        lang = "en"

[menu]
  [[menu.main]]
    identifier = "github"
    name = "github"
    url = "https://github.com/shlyapp"
    weight = 20
  [[menu.main]]
    identifier = "tg"
    name = "telegram"
    url = "https://t.me/selfdoor"
    weight = 30
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 5